import { Token, ChainId } from '@monadex/sdk'
import { parseBytes32String } from '@ethersproject/strings'
import { useMemo } from 'react'
import { useBytes32TokenContract, useTokenContract } from './useContracts'
import { NEVER_RELOAD, useSingleCallResult } from '@/state/multicall/hooks'
import { useCombinedInactiveList, useCombinedActiveList } from '@/state/list/hooks'
import { useUserAddedTokens } from '@/state/user/hooks'
import { isAddress } from 'viem'
import { TokenAddressMap } from '@/state/list/hooks'
import MONADEXV2ROUTERABI from "@/constants/abi/JSON/MonadexRouterV1.json"
import { ROUTER_ADDRESS } from '@/constants/index'
import { useWallets } from '@web3-onboard/react'
